### ISSUE TITLE
Getting Error While Adding Task

### ISSUE THREAD

**Issue by Sledger9** [Sam-Max/rcmltb#148] opened 2023-05-28 17:54 UTC
2023-05-28 17:50:45,702 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-1666' coro=<setInterval.setInterval() done, defined at /usr/src/app/bot/helper/ext_utils/bot_utils.py:218> exception=TypeError('A coroutine object is required')>
Traceback (most recent call last):
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 221, in setInterval
    await self.action()
  File "/usr/src/app/bot/helper/telegram_helper/message_utils.py", line 126, in update_all_messages
    msg, buttons = await run_sync(get_readable_message)
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 232, in run_sync
    return await future
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 140, in get_readable_message
    msg += f"\n<b>Processed:</b> {download.processed_bytes()} of {download.size()}"
  File "/usr/src/app/bot/helper/mirror_leech_utils/status_utils/zip_status.py", line 57, in processed_bytes
    return get_readable_file_size(self.processed_raw())
  File "/usr/src/app/bot/helper/mirror_leech_utils/status_utils/zip_status.py", line 54, in processed_raw
    return run_async(get_path_size, self.__listener.dir) - self.__size
  File "/usr/src/app/bot/helper/ext_utils/bot_utils.py", line 237, in run_async
    future = run_coroutine_threadsafe(func(*args, **kwargs), botloop)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 872, in run_coroutine_threadsafe
    raise TypeError('A coroutine object is required')
TypeError: A coroutine object is required
2023-05-28 17:51:40,018 - bot - INFO - Cleaning Target

**Comment by Sam-Max** [comment] 2023-05-29 02:33
Update to last commit

**Comment by Sledger9** [comment] 2023-05-29 02:35
> Update to last commit

Yes using the same but still getting same error

**Comment by Sam-Max** [comment] 2023-05-29 03:03
> > Update to last commit
> 
> Yes using the same but still getting same error

Join telegram channel and send me logs there

**Comment by Sam-Max** [comment] 2023-05-29 06:23
Closing this, as you did not send report to telegram channel and cannot reproduce this error

**Closed by Sam-Max** 2023-05-29 06:23 UTC
